# Use the official MySQL image as the base image
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=travelhub
ENV MYSQL_USER=tester
ENV MYSQL_PASSWORD=test@123

# Optionally, copy custom MySQL configuration files if needed
# COPY custom-config.cnf /etc/mysql/conf.d/

# Optionally, copy SQL initialization scripts to create tables, insert data, etc.
# COPY init.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
