version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=travelhub
    ports:
      - "3306:3306"  # Forward MySQL port 3306 from container to host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Health check command for MySQL
      timeout: 10s
      retries: 5

  travelhub-springboot:
    image: travelhub.azurecr.io/backend:latest
    container_name: travelhub-springboot
    ports:
      - "8080:8080"  # Forward Spring Boot app port 8080 from container to host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalone:3306/travelhub?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql-standalone:
        condition: service_healthy # Wait for the MySQL service to be healthy before starting
