version: '3'

services:
    mysql-standalone:
      image: mysql:latest
      container_name: mysql-standalone
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=travelhub
        - MYSQL_USER=test   
        - MYSQL_PASSWORD=root
      ports:
        - 3306:3306
    travelhub-springboot:
      image: travelhub-backend
      container_name: travelhub-springboot
      ports:
        - 8080:8080
      build:
        context: ./
        dockerfile: Dockerfile

      depends_on:
        - mysql-standalone
