name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Backend and Frontend Docker images
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./TravelHub-Backend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./TravelHub-frontend

      - name: Push Backend and Frontend Docker images to Azure Container Registry
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Deploy Backend and Frontend to Azure Container Instances
        uses: azure/container-instances-deploy@1
        with:
          resource-group: RLDS
          name: travelhub-container
          image: ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest,${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
          dns-name-label: travelhub-container
          os-type: Linux
          cpu: 1
          memory: 1.5
          environment-variables: |
            - name: MYSQL_HOST
              value: mysql-standalone
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "travelhub"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"

      - name: Check Deployment Status
        run: |
          curl -sSfL http://travelhub-container.westus.azurecontainer.io/ || echo "Application is not responding"
