name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Change 'main' to your branch name if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Adjust OS if needed
    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd TravelHub-backend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/travelhub-backend:latest .  # Replace placeholders

      - name: Push Docker Image to ACR
        run: |
          cd TravelHub-backend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/travelhub-backend:latest
