name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
           cd TravelHub-Backend
           docker build -t reshma784/my-spring-boot-app .
      - name: Push Docker image to Docker Hub
        run: docker push reshma784/my-spring-boot-app

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull reshma784/my-spring-boot-app

      - name: Run Docker container
        run: docker run -d -p 8080:8080 reshma784/my-spring-boot-app
