name: Deploy App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend Project
        run: |
          cd TravelHub-Backend
          mvn clean install -DskipTests

      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: TravelHub-Backend/target/*.jar

  frontend:
    name: Frontend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Frontend Docker image
        run: |
          cd TravelHub-frontend
          npm install
          ng build --configuration=production
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Frontend Docker image to Azure Container Registry
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

  deploy:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: TravelHub-Backend/target/*.jar

      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: TravelHubweb
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: 'TravelHub-Backend/target/*.jar'
