name: Java Maven CI with Spring Boot and MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          java-package: jdk

      - name: Build with Maven
        run: |
          cd TravelHub-Backend
          mvn clean install

      - name: Connect to MySQL
        run: |
          cd TravelHub-Backend
          mvn spring-boot:run
