name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_mysql:
    name: Build MySQL Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build MySQL Docker image
        run: |
           cd TravelHub-Backend
           docker build -f Dockerfile.mysql -t reshma784/my-mysql-db .

  build_spring_boot:
    name: Build and Push Spring Boot Docker Image
    runs-on: ubuntu-latest
    needs: build_mysql
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Spring Boot Docker image
        run: |
           cd TravelHub-Backend
           docker build -t reshma784/my-spring-boot-app .

      - name: Push Spring Boot Docker image to Docker Hub
        run: docker push reshma784/my-spring-boot-app

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build_spring_boot
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull reshma784/my-spring-boot-app

      - name: Run Docker container
        run: docker run -p 8080:8080 reshma784/my-spring-boot-app
