name: Build and Deploy Spring Boot Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Adjust OS if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout code from your repository
      
      # Docker Hub Login (if using Docker Hub)
      - name: Login to Docker Hub
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Spring Boot Image
      - name: Build Spring Boot Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/travelhub-backend:latest .
      
      # Build Angular Image
      - name: Build Angular Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/travelhub-frontend:latest .
      
      # Push Spring Boot Image (if using Docker Hub)
      - name: Push Spring Boot Image
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/travelhub-backend:latest
      
      # Push Angular Image (if using Docker Hub)
      - name: Push Angular Image
        if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/travelhub-frontend:latest
      
      # Deploy to Azure App Service (Optional)
      - name: Deploy to Azure App Service
        if: secrets.AZURE_WEBAPP_PUBLISH_PROFILE != ''
        uses: azure/webapps-deploy@v2
        with:
          resourceGroup: RLDS
          appService: TravelHubWeb
          package: .  # Use a specific deployment package if needed
          publishProfile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Service Principal credentials
