name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend_build_and_deployment:
    name: Backend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Backend
        run: |
          cd TravelHub-Backend
          mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag ${{ secrets.ACR_NAME }}/project .
          docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push ${{ secrets.ACR_NAME }}/project
