name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull Backend Docker image
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

      - name: Pull Frontend Docker image
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Deploy Backend Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: travelhubweb
          slot-name: production # Optional: specify deployment slot
          images: ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

      - name: Deploy Frontend Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: travelhubweb
          slot-name: production # Optional: specify deployment slot
          images: ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
