name: workflow

on:
  push:
    branches: [main]

jobs:
  frontend:
    name: Frontend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build Frontend Docker image
        run: |
          cd TravelHub-frontend
          npm install
          ng build --configuration=production
          docker build -t ${{ secrets.DOCKER_USERNAME }}/travehub-frontend:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/travehub-frontend:latest
