name: workflow

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Backend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: |
          cd TravelHub-Backend
          mvn clean package -DskipTests

      - name: Build and run Backend
        run: |
          cd TravelHub-Backend
          docker-compose up --build -d

  frontend:
    name: Frontend Build and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build and run Frontend
        run: |
          cd TravelHub-frontend
          docker-compose up --build
