name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Frontend Docker image
        run: |
          cd TravelHub-frontend
          npm install
          ng build --configuration=production
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/travehub-frontend:latest .
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Frontend Docker image to Azure Container Registry
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/travehub-frontend:latest
